# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meeting',
            unique_together=set([('property', 'date')]),
        ),
    ]
